BEGIN;

CREATE TYPE "Инструктаж_статус_enum" AS ENUM (
  'Запланирован',
  'В процессе',
  'Завершено',
  'Отменено',
  'Необходим повтор'
);

CREATE TYPE "Инструктаж_тип_enum" AS ENUM (
  'Ориентационный',
  'Вводный',
  'Плановый',
  'Целевой',
  'Дополнительный',
  'Специальный'
);

CREATE TYPE "Работа_тип_enum" AS ENUM (
  'Перемещение',
  'Ремонт',
  'Складское задание'
);

CREATE TYPE "Тип_объекта_enum" AS ENUM (
  'Оборудование',
  'Работа'
);

CREATE TYPE "Место_хранения_тип_enum" AS ENUM (
  'Склад',
  'Цех'
);

CREATE TABLE "Категории_оборудования" (
  "id_категории" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "категория" VARCHAR(100) NOT NULL,
  "подкатегория" VARCHAR(100)
);

CREATE TABLE "График_обслуживания" (
  "id_обслуживания" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_категории" INT NOT NULL,
  "тип_обслуживания" VARCHAR(100) NOT NULL,
  "частота_обслуживания" INT NOT NULL,
  "единица_измерения_частоты" VARCHAR(10) NOT NULL
);

CREATE TABLE "Оборудование" (
  "id_оборудования" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "наименование" VARCHAR(100) NOT NULL,
  "описание_на_русском" VARCHAR(1000) NOT NULL,
  "описание_на_английском" VARCHAR(1000),
  "серийный_номер" VARCHAR(50),
  "наименование_детали_модели" VARCHAR(100) UNIQUE NOT NULL,
  "id_закупки_оборудования" INT NOT NULL,
  "стоимость" INT NOT NULL,
  "единица_измерения_цены" VARCHAR(50) NOT NULL DEFAULT 'рубли',
  "id_категории" INT NOT NULL
);

CREATE TABLE "Поставщики" (
  "id_поставщика" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "название" VARCHAR(100) NOT NULL,
  "описание" VARCHAR(100),
  "адрес" VARCHAR(255),
  "телефон" VARCHAR(20),
  "email" VARCHAR(100) NOT NULL
);

CREATE TABLE "Закупка_оборудования" (
  "id_закупки_оборудования" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_поставщика" INT NOT NULL,
  "дата_закупки" DATE NOT NULL
);

CREATE TABLE "Сотрудник" (
  "id_сотрудника" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "фамилия" VARCHAR(100) NOT NULL,
  "имя" VARCHAR(100) NOT NULL,
  "отчество" VARCHAR(100),
  "дата_рождения" DATE NOT NULL,
  "табельный_номер" VARCHAR(50) UNIQUE,
  "должность" VARCHAR(100),
  "номер_телефон" VARCHAR(20),
  "дата_трудоустройства" DATE,
  "дата_увольнения" DATE
);

CREATE TABLE "Сотрудник_Инструктаж" (
  "id_сотрудника" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "id_инструктажа" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  PRIMARY KEY ("id_сотрудника", "id_инструктажа")
);

CREATE TABLE "Инструктаж" (
  "id_инструктажа" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "дата_проведения" DATE,
  "тип_инструктажа" Инструктаж_тип_enum NOT NULL DEFAULT 'Плановый',
  "частота_проведения" INT,
  "единица_измерения_частоты" VARCHAR(10) NOT NULL,
  "статус" Инструктаж_статус_enum NOT NULL DEFAULT 'Запланирован'
);

CREATE TABLE "Работа" (
  "id_работы" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "тип_работы" Работа_тип_enum NOT NULL,
  "id_оборудования" INT,
  "описание" TEXT,
  "id_ответственного" INT NOT NULL,
  "id_куда" INT
);

CREATE TABLE "Статус_Работа" (
  "id_статуса" INT GENERATED BY DEFAULT AS IDENTITY,
  "id_работы" INT GENERATED BY DEFAULT AS IDENTITY,
  "дата_изменения_статуса" DATE NOT NULL,
  PRIMARY KEY ("id_статуса", "id_работы")
);

CREATE TABLE "Статус" (
  "id_статуса" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "тип_объекта" Тип_объекта_enum NOT NULL,
  "название" VARCHAR(50) UNIQUE NOT NULL,
  "описание" VARCHAR(255)
);

CREATE TABLE "Место_хранения" (
  "id_места" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "тип" Место_хранения_тип_enum NOT NULL,
  "зона" VARCHAR(100),
  "номер_ряда" INT,
  "номер_ячейки" INT,
  "название_цеха" VARCHAR(100),
  "описание_цеха" VARCHAR(200)
);

CREATE TABLE "Статус_Оборудование" (
  "id_статуса" INT GENERATED BY DEFAULT AS IDENTITY,
  "id_оборудования" INT GENERATED BY DEFAULT AS IDENTITY,
  "дата_изменения_статуса" DATE NOT NULL,
  PRIMARY KEY ("id_статуса", "id_оборудования")
);

CREATE TABLE "Правило_статус" (
  "id_правила" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_текущий_статус" INT,
  "id_новый_статус" INT
);

ALTER TABLE "Оборудование" ADD FOREIGN KEY ("id_закупки_оборудования") REFERENCES "Закупка_оборудования" ("id_закупки_оборудования") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "Закупка_оборудования" ADD FOREIGN KEY ("id_поставщика") REFERENCES "Поставщики" ("id_поставщика") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "Сотрудник_Инструктаж" ADD FOREIGN KEY ("id_сотрудника") REFERENCES "Сотрудник" ("id_сотрудника") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "Сотрудник_Инструктаж" ADD FOREIGN KEY ("id_инструктажа") REFERENCES "Инструктаж" ("id_инструктажа") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "Статус_Работа" ADD FOREIGN KEY ("id_работы") REFERENCES "Работа" ("id_работы") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "Работа" ADD FOREIGN KEY ("id_оборудования") REFERENCES "Оборудование" ("id_оборудования") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "Статус_Работа" ADD FOREIGN KEY ("id_статуса") REFERENCES "Статус" ("id_статуса") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "График_обслуживания" ADD FOREIGN KEY ("id_категории") REFERENCES "Категории_оборудования" ("id_категории") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "Оборудование" ADD FOREIGN KEY ("id_категории") REFERENCES "Категории_оборудования" ("id_категории") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "Статус_Оборудование" ADD FOREIGN KEY ("id_статуса") REFERENCES "Статус" ("id_статуса") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "Статус_Оборудование" ADD FOREIGN KEY ("id_оборудования") REFERENCES "Оборудование" ("id_оборудования") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "Правило_статус" ADD FOREIGN KEY ("id_текущий_статус") REFERENCES "Статус" ("id_статуса") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "Правило_статус" ADD FOREIGN KEY ("id_новый_статус") REFERENCES "Статус" ("id_статуса") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "Работа" ADD FOREIGN KEY ("id_ответственного") REFERENCES "Сотрудник" ("id_сотрудника");

ALTER TABLE "Работа" ADD FOREIGN KEY ("id_куда") REFERENCES "Место_хранения" ("id_места");


COMMIT;